# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 07:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserToDateTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('user_name', models.CharField(max_length=14)),
                ('date', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UserToReadUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('user_name', models.CharField(max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='UserToRecommendUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('user_name', models.CharField(max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='UserToTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50)),
                ('user_name', models.CharField(max_length=14)),
                ('weight', models.PositiveIntegerField()),
            ],
        ),
    ]
