# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 07:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('nick_name', models.CharField(max_length=14)),
                ('user_name', models.CharField(max_length=14, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='UserToKind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=14)),
                ('kind', models.CharField(max_length=50)),
            ],
        ),
    ]
