# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 07:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('title', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('kind', models.CharField(max_length=50)),
                ('hot_rate', models.FloatField()),
                ('date', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='NewsToLimitTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='NewsToTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=200)),
            ],
        ),
    ]
